module.exports = {
  ...require('jest-preset-angular/jest-preset'),
  rootDir: '.',
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  testMatch: ['**/*.spec.ts'],
  moduleFileExtensions: ['ts', 'html', 'js', 'json', 'mjs'],
  moduleNameMapper: {
    '^@api$': '<rootDir>/src/app/api/index.ts',
    '^@components/(.*)$': '<rootDir>/src/app/components/$1',
    '^@core/(.*)$': '<rootDir>/src/app/core/$1',
    '^@features/(.*)$': '<rootDir>/src/app/features/$1',
    '^@app-types/(.*)$': '<rootDir>/src/app/types/$1',
    '^@pages/(.*)$': '<rootDir>/src/app/pages/$1',
    '^@utils/(.*)$': '<rootDir>/src/app/utils/$1',
    '^@test-utils/(.*)$': '<rootDir>/src/app/test-utils/$1',
    '^@custom-form/(.*)$': '<rootDir>/src/app/features/custom-form/$1',
    '^@custom-form-validators/(.*)$': '<rootDir>/src/app/features/custom-form-validators/$1',
    '^@auth-module/(.*)$': '<rootDir>/src/app/modules/auth-module/$1',
    '^@env$': '<rootDir>/src/environment/environment',
    '^@user-module/(.*)$': '<rootDir>/src/app/modules/user-module/$1',
    '^@product-module/(.*)$': '<rootDir>/src/app/modules/product-module/$1',
    '^@cart-module/(.*)$': '<rootDir>/src/app/modules/cart-module/$1',
    '^@checkout-module/(.*)$': '<rootDir>/src/app/modules/checkout-module/$1',
  },
  transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$)'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.spec.ts',
    '!src/**/*.d.ts',
    '!src/main.ts',
    '!src/server.ts',
  ],
  coverageDirectory: '<rootDir>/coverage',
  coverageReporters: ['html', 'text-summary'],
};
